export { default as Welcome } from "./Welcome";
export { default as Services } from "./Services";
export { default as NavBar } from "./NavBar";
export { default as Loader } from "./Loader";
export { default as Footer } from "./Footer";
export { default as Online } from "./online";
export { default as Error } from "./Error";
export { default as Ticket } from "./Ticket";
export { default as Donate } from './Donate'